### ISSUE TITLE
TODO (23/12/18 ~ 23/12/24)

### ISSUE THREAD

**Issue by Bhanjo** [mju-likelion/inception#100]
## TODO
- [x] 리팩토링 가이드 완성
- [x] 현재 프로젝트 문제점 분석
- [x] 리팩토링 참여자에게 리팩토링 방향성 설명 및 목표 부여
- [x] 리팩토링 전 프로젝트 분석 (문제점 및 기능, 플로우 확인)
